#!/bin/sh
# Fixture for Task 3 (survival guard in mb_select_sub).
#
# Reference:
#   chrP      400bp unique (non-repetitive) sequence generated by LCG.
#   chrP_alt  ALT = chrP with a 1bp SNP at 1-based position 126 (0-based 125).
#             .alt CIGAR: 400M (full length alignment, 1 mismatch at 125).
#
# Read "r-survive" (100bp, chrP[70,170), 1-based 71..170):
#   The SNP is at read position 55 (0-based: read[55] = chrP[125]).
#
#   Seeding / chaining behaviour with the unique sequence:
#     - chrP gets one 100bp anchor (qs=0, ts=70): chain score ~100.
#     - chrP_alt gets one ~55bp sub-SMEM anchor (qs=0, ts=70) because the
#       interval with both chrP and chrP_alt contracts at length 56 (the SNP
#       position).  Chain score ~55.
#
#   mb_select_sub with -p 0.9 (pri_ratio=0.9), default min_diff=2*min_len=38:
#     keep if: score >= parent * 0.9  OR  score + 38 >= parent
#     parent_score = 100:
#       55 >= 90   -> FALSE
#       55 + 38 = 93 >= 100 -> FALSE
#     => chrP_alt twin DROPPED without the guard.
#
#   After the guard: chrP_alt is force-kept because its lifted placement
#   (lifted to chrP ts~70) co-locates with the kept chrP primary.
set -eu
d="$1"; mkdir -p "$d"

# Build a 400bp unique sequence (LCG PRNG, seed 42)
S=$(python3 -c "
import random
random.seed(42)
n='ACGT'
print(''.join(random.choice(n) for _ in range(400)))
")
L=${#S}

# SNP at 1-based position 126 (0-based 125)
# This puts the SNP at read position 55 (read starts at chrP[70,170), so
# SNP position = 125 - 70 = 55 within the read).
C=$(printf '%s' "$S" | cut -c126)
FLIP=$(printf '%s' "$C" | tr 'ACGTacgt' 'TGCAtgca')
PREFIX=$(printf '%s' "$S" | cut -c1-125)
SUFFIX=$(printf '%s' "$S" | cut -c127-)
ALT="${PREFIX}${FLIP}${SUFFIX}"

# --- reference ---
printf '>chrP\n%s\n' "$S" > "$d/ref.fa"
printf '>chrP_alt\n%s\n' "$ALT" >> "$d/ref.fa"

# --- .alt (400M: full-length alignment, 1 mismatch at 0-based position 125) ---
printf 'chrP_alt\t0\tchrP\t1\t60\t%dM\t*\t0\t0\t*\t*\n' "$L" > "$d/ref.fa.alt"

# --- read: chrP[70,170) 1-based 71..170 (100bp) ---
READ=$(printf '%s' "$S" | cut -c71-170)
QUAL=$(printf '%100s' '' | tr ' ' 'I')
printf '@r-survive\n%s\n+\n%s\n' "$READ" "$QUAL" > "$d/reads.fq"

echo "fixture: L=$L  chrP_alt(SNP@125  $C->$FLIP)  read=chrP[70,170) SNP at read-pos 55" >&2
