name: build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: make -j$(nproc)
      - run: make -j$(nproc) -C api-test
      - name: meth alignment functional test
        run: sh test/test-meth-align.sh
